home:
  path : /
  controller : App\Controller\SecurityController::login

index : 
  path : /accueil
  controller : App\Controller\PagesController::home

#index:
#    path: /
#    controller: App\Controller\DefaultController::index
