<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEw274US\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEw274US/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEw274US.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEw274US\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerEw274US\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'Ew274US',
    'container.build_id' => 'e35a5d1e',
    'container.build_time' => 1551952318,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerEw274US');
