<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXhbxlHX\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXhbxlHX/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXhbxlHX.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXhbxlHX\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXhbxlHX\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'XhbxlHX',
    'container.build_id' => 'a047dcbf',
    'container.build_time' => 1551708827,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXhbxlHX');
